// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . 3 . . . . . . . . . . . 
. . . . 3 . . . . . . . . . . . 
. . . . 3 . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image2":
            case "neutral":return img`
................
................
................
................
......bbbb......
....bbbccb......
....bcccccb.....
....bcccccbb....
....bbbccccb....
...bbbbcccbb....
...bccbbbbb.....
...bccbbb.......
...bcccbb.......
..bbcccbb.......
.bbccccbb.......
.bcccccbb.......
.bcccccbb.......
.bcccccbbb......
.bccccccbb......
.bccccccbbb.....
.bcccccccbb.....
.bcccccccbb.....
.bbccccccbbb....
..bcccccbbbb....
..bcccccbbb.....
..bbcccbbb......
..bbcccbb.......
..bcccccb.......
..bcccccb.......
..bcccccb.......
..bccccb........
..bccccb........
..bccccb........
..bccccb........
..bccccb........
..bccccb........
..bbcccb........
...bcccb........
...bcccb........
...bbcbb........
....bbbbbb......
.....bbcccb.....
.....bbbbb......
................
................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
