namespace SpriteKind {
    export const protection = SpriteKind.create()
}
function createCharacter () {
    canJump = 1
    direction = "right"
    movementSpeed = 120
    person = sprites.create(assets.image`neutral`, SpriteKind.Player)
    person.setPosition(14, 130)
    person.ay = 100
    scene.cameraFollowSprite(person)
    neutralAnim()
}
function createLevel () {
    scene.setTileMap(img`
        ............................................................
        ............................................................
        ............................................................
        ............................................................
        ............................................................
        ............................................................
        ............................................................
        ............................................................
        ............................................................
        ............................................................
        ......d.........d..................d.............d......d...
        777777777777777777777777777777777777777777777777777777777777
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        `)
    scene.setBackgroundImage(img`
        1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
        1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
        1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
        1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
        1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
        1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
        1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
        1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
        1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
        1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
        1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
        1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
        1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
        1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
        1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
        1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
        1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
        1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
        1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
        11111111111111111dddd111111111111111111111111111111111111dddd111111111111111111111111111111111111dddd111111111111111111111111111111111111dddd1111111111111111111
        11111111111ddddddddddd11111111111111111111111111111ddddddddddd11111111111111111111111111111ddddddddddd11111111111111111111111111111ddddddddddd111111111111111111
        11111111dddddddddddddd11111111111111111111111111dddddddddddddd11111111111111111111111111dddddddddddddd11111111111111111111111111dddddddddddddd111111111111111111
        111111dddddddddddddddd111111111111111111111111dddddddddddddddd111111111111111111111111dddddddddddddddd111111111111111111111111dddddddddddddddd111111111111111111
        11111ddddddddddddddddd11111111111111111111111ddddddddddddddddd11111111111111111111111ddddddddddddddddd11111111111111111111111ddddddddddddddddd111111111111111111
        11111ddddddddddddddddd11111111111111111111111ddddddddddddddddd11111111111111111111111ddddddddddddddddd11111111111111111111111ddddddddddddddddd111111111111111111
        1111ddddddddddddddddddd111111111111111111111ddddddddddddddddddd111111111111111111111ddddddddddddddddddd111111111111111111111ddddddddddddddddddd11111111111111111
        1111ddddddddddddddddddd111111111111111111111ddddddddddddddddddd111111111111111111111ddddddddddddddddddd111111111111111111111ddddddddddddddddddd11111111111111111
        111dddddddddddddddddddd111111ddd11111111111dddddddddddddddddddd111111ddd11111111111dddddddddddddddddddd111111ddd11111111111dddddddddddddddddddd111111ddd11111111
        111dddddddddddddddddddd11111ddddd1111111111dddddddddddddddddddd11111ddddd1111111111dddddddddddddddddddd11111ddddd1111111111dddddddddddddddddddd11111ddddd1111111
        11ddddddddddddddddddddd11111ddddd111111111ddddddddddddddddddddd11111ddddd111111111ddddddddddddddddddddd11111ddddd111111111ddddddddddddddddddddd11111ddddd1111111
        11ddddddddddddddddddddd11111ddddd111111111ddddddddddddddddddddd11111ddddd111111111ddddddddddddddddddddd11111ddddd111111111ddddddddddddddddddddd11111ddddd1111111
        11ddddddddddddddddddddd11111dddddd11111111ddddddddddddddddddddd11111dddddd11111111ddddddddddddddddddddd11111dddddd11111111ddddddddddddddddddddd11111dddddd111111
        1dddddddddddddddddddddd11111dddddd1111111dddddddddddddddddddddd11111dddddd1111111dddddddddddddddddddddd11111dddddd1111111dddddddddddddddddddddd11111dddddd111111
        1dddddddddddddddddddddd11111dddddd1111111dddddddddddddddddddddd11111dddddd1111111dddddddddddddddddddddd11111dddddd1111111dddddddddddddddddddddd11111dddddd111111
        1dddddddddddddddddddddd1111ddddddd1111111dddddddddddddddddddddd1111ddddddd1111111dddddddddddddddddddddd1111ddddddd1111111dddddddddddddddddddddd1111ddddddd111111
        dddddddddddddddcddddddd1111ddddddd1111dddddddddddddddddcddddddd1111ddddddd1111dddddddddddddddddcddddddd1111ddddddd1111dddddddddddddddddcddddddd1111ddddddd1111dd
        ddddddddddddddccddddddd1111ddddddd11ddddddddddddddddddccddddddd1111ddddddd11ddddddddddddddddddccddddddd1111ddddddd11ddddddddddddddddddccddddddd1111ddddddd11dddd
        ddddddddddddddccddddddd1111dddddddd1ddddddddddddddddddccddddddd1111dddddddd1ddddddddddddddddddccddddddd1111dddddddd1ddddddddddddddddddccddddddd1111dddddddd1dddd
        dddddddddddddccccdddddd1111ddddddddddddddddddddddddddccccdddddd1111ddddddddddddddddddddddddddccccdddddd1111ddddddddddddddddddddddddddccccdddddd1111ddddddddddddd
        dddddddddddcccccdddddddddddddddddddddddddddddddddddcccccdddddddddddddddddddddddddddddddddddcccccdddddddddddddddddddddddddddddddddddcccccdddddddddddddddddddddddd
        dddddddddddddcccdddddddddddddddbbbbbbbdddddddddddddddcccdddddddddddddddbbbbbbbdddddddddddddddcccdddddddddddddddbbbbbbbdddddddddddddddcccdddddddddddddddbbbbbbbdd
        ddddddddddddcccccddddddddddddbbbbbbbbbbbddddddddddddcccccddddddddddddbbbbbbbbbbbddddddddddddcccccddddddddddddbbbbbbbbbbbddddddddddddcccccddddddddddddbbbbbbbbbbb
        bdddddddddddcccccccdddddddddbbbbbbbbbbbbbdddddddddddcccccccdddddddddbbbbbbbbbbbbbdddddddddddcccccccdddddddddbbbbbbbbbbbbbdddddddddddcccccccdddddddddbbbbbbbbbbbb
        bbbddddddddccccccdddddddddbbbbbbbbbbbbbbbbbddddddddccccccdddddddddbbbbbbbbbbbbbbbbbddddddddccccccdddddddddbbbbbbbbbbbbbbbbbddddddddccccccdddddddddbbbbbbbbbbbbbb
        bbbbdddddcccccccccdddddddbbbbbbbbbbbbbbbbbbbdddddcccccccccdddddddbbbbbbbbbbbbbbbbbbbdddddcccccccccdddddddbbbbbbbbbbbbbbbbbbbdddddcccccccccdddddddbbbbbbbbbbbbbbb
        bbbbbddddddccccccccdddddbbbbbbbbbbbbbbbbbbbbbddddddccccccccdddddbbbbbbbbbbbbbbbbbbbbbddddddccccccccdddddbbbbbbbbbbbbbbbbbbbbbddddddccccccccdddddbbbbbbbbbbbbbbbb
        bbbbbbddbbcccccccddddddbbbbbbbbbbbbbbbbbbbbbbbddbbcccccccddddddbbbbbbbbbbbbbbbbbbbbbbbddbbcccccccddddddbbbbbbbbbbbbbbbbbbbbbbbddbbcccccccddddddbbbbbbbbbbbbbbbbb
        bbbbbbbbbbbbccccccddddbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccddddbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccddddbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccddddbbcbbbbbbbbbbbbbbb
        bbbbbbbbbbcccccccccddbbbcbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccddbbbcbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccddbbbcbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccddbbbcbbbbbbbbbbbbbbb
        bbbbbbbbbcccccccccccbbbccbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccbbbccbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccbbbccbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccbbbccbbbbbbbbbbbbbbb
        bbbbbbbcccccccccccbbbbbbccbbbbbbbbbbbbbbbbbbbbbcccccccccccbbbbbbccbbbbbbbbbbbbbbbbbbbbbcccccccccccbbbbbbccbbbbbbbbbbbbbbbbbbbbbcccccccccccbbbbbbccbbbbbbbbbbbbbb
        bbbbbbbbbcccccccccbbbbbccbbbbbbbbbbbbbbbbbbbbbbbbcccccccccbbbbbccbbbbbbbbbbbbbbbbbbbbbbbbcccccccccbbbbbccbbbbbbbbbbbbbbbbbbbbbbbbcccccccccbbbbbccbbbbbbbbbbbbbbb
        bbbbbbbbbcccccccbbbbbbccccbbbbbbbbbbbbbbbbbbbbbbbcccccccbbbbbbccccbbbbbbbbbbbbbbbbbbbbbbbcccccccbbbbbbccccbbbbbbbbbbbbbbbbbbbbbbbcccccccbbbbbbccccbbbbbbbbbbbbbb
        bbbbbbbbccbccccccccbbccccccbbbbbbbbbbbbbbbbbbbbbccbccccccccbbccccccbbbbbbbbbbbbbbbbbbbbbccbccccccccbbccccccbbbbbbbbbbbbbbbbbbbbbccbccccccccbbccccccbbbbbbbbbbbbb
        bbbbbbbbbbccccccccccbbbccbbbbbbbbbbbcbbbbbbbbbbbbbccccccccccbbbccbbbbbbbbbbbcbbbbbbbbbbbbbccccccccccbbbccbbbbbbbbbbbcbbbbbbbbbbbbbccccccccccbbbccbbbbbbbbbbbcbbb
        bbbbbbbbcccccccccccbbccccccbbbbbbbbbcbbbbbbbbbbbcccccccccccbbccccccbbbbbbbbbcbbbbbbbbbbbcccccccccccbbccccccbbbbbbbbbcbbbbbbbbbbbcccccccccccbbccccccbbbbbbbbbcbbb
        bbbcbbbccccccccccccbccccccccbbbbbbbcccbbbbbcbbbccccccccccccbccccccccbbbbbbbcccbbbbbcbbbccccccccccccbccccccccbbbbbbbcccbbbbbcbbbccccccccccccbccccccccbbbbbbbcccbb
        bbbccbbbbbccccccccccccccccbbbbbbbbbbccbbbbbccbbbbbccccccccccccccccbbbbbbbbbbccbbbbbccbbbbbccccccccccccccccbbbbbbbbbbccbbbbbccbbbbbccccccccccccccccbbbbbbbbbbccbb
        bbccbbbbccccccccccccccccccccbbbbbbbccbbbbbccbbbbccccccccccccccccccccbbbbbbbccbbbbbccbbbbccccccccccccccccccccbbbbbbbccbbbbbccbbbbccccccccccccccccccccbbbbbbbccbbb
        bbbccbbccccccccccccccccccccccbbbbbccccbbbbbccbbccccccccccccccccccccccbbbbbccccbbbbbccbbccccccccccccccccccccccbbbbbccccbbbbbccbbccccccccccccccccccccccbbbbbccccbb
        bbcccccccccccccccccccccccccbbbbbbbbccccbbbcccccccccccccccccccccccccbbbbbbbbccccbbbcccccccccccccccccccccccccbbbbbbbbccccbbbcccccccccccccccccccccccccbbbbbbbbccccb
        bbbccccccccccccccccccccccccccbbbbbccccbbbbbccccccccccccccccccccccccccbbbbbccccbbbbbccccccccccccccccccccccccccbbbbbccccbbbbbccccccccccccccccccccccccccbbbbbccccbb
        bbbcccccccccccccccccccccccccccbbbccccccbbbbcccccccccccccccccccccccccccbbbccccccbbbbcccccccccccccccccccccccccccbbbccccccbbbbcccccccccccccccccccccccccccbbbccccccb
        bbccccccccccccccccccccccccccbbbbbbccccbbbbccccccccccccccccccccccccccbbbbbbccccbbbbccccccccccccccccccccccccccbbbbbbccccbbbbccccccccccccccccccccccccccbbbbbbccccbb
        bcccccccccccccccccccccccccccccbbcccccccbbcccccccccccccccccccccccccccccbbcccccccbbcccccccccccccccccccccccccccccbbcccccccbbcccccccccccccccccccccccccccccbbcccccccb
        bbcccccccccccccccccccccccccccccbbcccccccbbcccccccccccccccccccccccccccccbbcccccccbbcccccccccccccccccccccccccccccbbcccccccbbcccccccccccccccccccccccccccccbbccccccc
        bbccccccccccccccccccccccccccccbbccccccccbbccccccccccccccccccccccccccccbbccccccccbbccccccccccccccccccccccccccccbbccccccccbbccccccccccccccccccccccccccccbbcccccccc
        cccccccccccccccccccccccccccccccbcccccccccccccccccccccccccccccccccccccccbcccccccccccccccccccccccccccccccccccccccbcccccccccccccccccccccccccccccccccccccccbcccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        `)
    scene.setBackgroundColor(12)
    scene.setTile(14, img`
        f f f f f f f f f f f f f f f f 
        f f f f f f f f f f f f f f f f 
        f f f f f f f f f f f f f f f f 
        f f f f f f f f f f f f f f f f 
        f f f f f f f f f f f f f f f f 
        f f f f f f f f f f f f f f f f 
        f f f f f f f f f f f f f f f f 
        f f f f f f f f f f f f f f f f 
        f f f f f f f f f f f f f f f f 
        f f f f f f f f f f f f f f f f 
        f f f f f f f f f f f f f f f f 
        f f f f f f f f f f f f f f f f 
        f f f f f f f f f f f f f f f f 
        f f f f f f f f f f f f f f f f 
        f f f f f f f f f f f f f f f f 
        f f f f f f f f f f f f f f f f 
        `, true)
    scene.setTile(7, img`
        . . e e b b b b b b b b e e . . 
        . e b b b b b b b b b b b b e . 
        e b b b b b b b b b b b b b b e 
        b b b b b b b b b b b b b b b b 
        b b b b b b b b b b b b b b b b 
        b b b b b b b b b b b b b b b b 
        b b b b b b b b b b b b b b b b 
        b b b b b b b b b b b b b b b b 
        b b b b b b b b b b b b b b b b 
        b b b b b e e e b b b b b b b b 
        e e b e e e e b b b e e b b b e 
        b b e e b b e b b b e e e e e b 
        b e e e b b e e e f f b b e b b 
        f e b b e f f e f e e f e e e f 
        f f e e e e e f f e e f f f f f 
        f f f f e e f f f f f f f f f f 
        `, true)
    scene.setTile(13, img`
        . . . . . c c b b b . . . . . . 
        . . . . c b d d d d b . . . . . 
        . . . . c d d d d d d b b . . . 
        . . . . c d d d d d d d d b . . 
        . . . c b b d d d d d d d b . . 
        . . . c b b d d d d d d d b . . 
        . c c c c b b b b d d d b b b . 
        . c d d b c b b b b b b b b d b 
        c b b d d d b b b b b d d b d b 
        c c b b d d d d d d d b b b d c 
        c b c c c b b b b b b b d d c c 
        c c b b c c c c b d d d b c c b 
        . c c c c c c c c c c c b b b b 
        . . c c c c c b b b b b b b c . 
        . . . . . . c c b b b b c c . . 
        . . . . . . . . c c c c . . . . 
        `, false)
}
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    direction = "left"
    moveAnim()
})
controller.right.onEvent(ControllerButtonEvent.Released, function () {
    release2 = 0
    neutralAnim()
    if (!(0 == release1 && 0 == release2)) {
        animation.stopAnimation(animation.AnimationTypes.All, person)
    }
})
controller.left.onEvent(ControllerButtonEvent.Released, function () {
    release1 = 0
    neutralAnim()
    if (!(0 == release1 && 0 == release2)) {
        animation.stopAnimation(animation.AnimationTypes.All, person)
    }
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    direction = "right"
    moveAnim()
})
function neutralAnim () {
    if (person.isHittingTile(CollisionDirection.Bottom)) {
        if ("right" == direction) {
            animation.runImageAnimation(
            person,
            [img`
                ................
                ................
                ................
                ................
                ................
                ......bbbb......
                ....bbbccb......
                ....bcccccb.....
                ....bcccccbb....
                ...bbbbccccb....
                ...bbbbcccbb....
                ...bccbbbbb.....
                ...bcccbb.......
                ..bbcccbb.......
                .bbccccbb.......
                .bcccccbb.......
                .bcccccbb.......
                .bcccccbbb......
                .bccccccbb......
                .bccccccbbb.....
                .bcccccccbb.....
                .bcccccccbb.....
                .bbccccccbbb....
                ..bcccccbbbb....
                ..bcccccbbb.....
                ..bbcccbbb......
                ..bbcccbb.......
                ..bcccccb.......
                ..bcccccb.......
                ..bcccccb.......
                ..bccccb........
                ..bccccb........
                ..bccccb........
                ..bccccb........
                ..bccccb........
                ..bccccb........
                ..bbcccb........
                ...bcccb........
                ...bcccb........
                ...bbcbb........
                ....bbbbbb......
                .....bbcccb.....
                .....bbbbb......
                ................
                ................
                `,img`
                ................
                ................
                ................
                ................
                ................
                ................
                ......bbbb......
                ....bbbccb......
                ....bcccccb.....
                ....bcccccbb....
                ...bbbbccccb....
                ...bbbbcccbb....
                ...bccbbbbb.....
                ...bcccbb.......
                ..bbcccbb.......
                .bbccccbb.......
                .bcccccbb.......
                .bcccccbb.......
                .bcccccbbb......
                .bccccccbb......
                .bccccccbbb.....
                .bcccccccbb.....
                .bcccccccbb.....
                .bbccccccbbb....
                ..bcccccbbbb....
                ..bcccccbbb.....
                ..bbcccbbb......
                ..bbcccbb.......
                ..bcccccb.......
                ..bcccccb.......
                ..bccccb........
                ..bccccb........
                ..bccccb........
                ..bccccb........
                ..bccccb........
                ..bccccb........
                ..bbcccb........
                ...bcccb........
                ...bcccb........
                ...bbcbb........
                ....bbbbbb......
                .....bbcccb.....
                .....bbbbb......
                ................
                ................
                `,img`
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ......bbbb......
                ....bbbccb......
                ....bcccccb.....
                ....bcccccbb....
                ...bbbbccccb....
                ...bbbbcccbb....
                ...bccbbbbb.....
                ...bcccbb.......
                ..bbcccbb.......
                .bbccccbb.......
                .bcccccbb.......
                .bcccccbb.......
                .bcccccbbb......
                .bccccccbb......
                .bccccccbbb.....
                .bcccccccbb.....
                .bcccccccbb.....
                .bbccccccbbb....
                ..bcccccbbbb....
                ..bcccccbbb.....
                ..bbcccbbb......
                ..bbcccbb.......
                ..bcccccb.......
                ..bcccccb.......
                ..bccccb........
                ..bccccb........
                ..bccccb........
                ..bccccb........
                ..bccccb........
                ..bbcccb........
                ...bcccb........
                ...bcccb........
                ...bbcbb........
                ....bbbbbb......
                .....bbcccb.....
                .....bbbbb......
                ................
                ................
                `,img`
                ................
                ................
                ................
                ................
                ................
                ................
                ......bbbb......
                ....bbbccb......
                ....bcccccb.....
                ....bcccccbb....
                ...bbbbccccb....
                ...bbbbcccbb....
                ...bccbbbbb.....
                ...bcccbb.......
                ..bbcccbb.......
                .bbccccbb.......
                .bcccccbb.......
                .bcccccbb.......
                .bcccccbbb......
                .bccccccbb......
                .bccccccbbb.....
                .bcccccccbb.....
                .bcccccccbb.....
                .bbccccccbbb....
                ..bcccccbbbb....
                ..bcccccbbb.....
                ..bbcccbbb......
                ..bbcccbb.......
                ..bcccccb.......
                ..bcccccb.......
                ..bccccb........
                ..bccccb........
                ..bccccb........
                ..bccccb........
                ..bccccb........
                ..bccccb........
                ..bbcccb........
                ...bcccb........
                ...bcccb........
                ...bbcbb........
                ....bbbbbb......
                .....bbcccb.....
                .....bbbbb......
                ................
                ................
                `],
            100,
            true
            )
        } else {
            animation.runImageAnimation(
            person,
            [img`
                ................
                ................
                ................
                ................
                ................
                ......bbbb......
                ....bbbccb......
                ....bcccccb.....
                ....bcccccbb....
                ...bbbbccccb....
                ...bbbbcccbb....
                ...bccbbbbb.....
                ...bcccbb.......
                ..bbcccbb.......
                .bbccccbb.......
                .bcccccbb.......
                .bcccccbb.......
                .bcccccbbb......
                .bccccccbb......
                .bccccccbbb.....
                .bcccccccbb.....
                .bcccccccbb.....
                .bbccccccbbb....
                ..bcccccbbbb....
                ..bcccccbbb.....
                ..bbcccbbb......
                ..bbcccbb.......
                ..bcccccb.......
                ..bcccccb.......
                ..bcccccb.......
                ..bccccb........
                ..bccccb........
                ..bccccb........
                ..bccccb........
                ..bccccb........
                ..bccccb........
                ..bbcccb........
                ...bcccb........
                ...bcccb........
                ...bbcbb........
                ....bbbbbb......
                .....bbcccb.....
                .....bbbbb......
                ................
                ................
                `,img`
                ................
                ................
                ................
                ................
                ................
                ................
                ......bbbb......
                ....bbbccb......
                ....bcccccb.....
                ....bcccccbb....
                ...bbbbccccb....
                ...bbbbcccbb....
                ...bccbbbbb.....
                ...bcccbb.......
                ..bbcccbb.......
                .bbccccbb.......
                .bcccccbb.......
                .bcccccbb.......
                .bcccccbbb......
                .bccccccbb......
                .bccccccbbb.....
                .bcccccccbb.....
                .bcccccccbb.....
                .bbccccccbbb....
                ..bcccccbbbb....
                ..bcccccbbb.....
                ..bbcccbbb......
                ..bbcccbb.......
                ..bcccccb.......
                ..bcccccb.......
                ..bccccb........
                ..bccccb........
                ..bccccb........
                ..bccccb........
                ..bccccb........
                ..bccccb........
                ..bbcccb........
                ...bcccb........
                ...bcccb........
                ...bbcbb........
                ....bbbbbb......
                .....bbcccb.....
                .....bbbbb......
                ................
                ................
                `,img`
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ......bbbb......
                ....bbbccb......
                ....bcccccb.....
                ....bcccccbb....
                ...bbbbccccb....
                ...bbbbcccbb....
                ...bccbbbbb.....
                ...bcccbb.......
                ..bbcccbb.......
                .bbccccbb.......
                .bcccccbb.......
                .bcccccbb.......
                .bcccccbbb......
                .bccccccbb......
                .bccccccbbb.....
                .bcccccccbb.....
                .bcccccccbb.....
                .bbccccccbbb....
                ..bcccccbbbb....
                ..bcccccbbb.....
                ..bbcccbbb......
                ..bbcccbb.......
                ..bcccccb.......
                ..bcccccb.......
                ..bccccb........
                ..bccccb........
                ..bccccb........
                ..bccccb........
                ..bccccb........
                ..bbcccb........
                ...bcccb........
                ...bcccb........
                ...bbcbb........
                ....bbbbbb......
                .....bbcccb.....
                .....bbbbb......
                ................
                ................
                `,img`
                ................
                ................
                ................
                ................
                ................
                ................
                ......bbbb......
                ....bbbccb......
                ....bcccccb.....
                ....bcccccbb....
                ...bbbbccccb....
                ...bbbbcccbb....
                ...bccbbbbb.....
                ...bcccbb.......
                ..bbcccbb.......
                .bbccccbb.......
                .bcccccbb.......
                .bcccccbb.......
                .bcccccbbb......
                .bccccccbb......
                .bccccccbbb.....
                .bcccccccbb.....
                .bcccccccbb.....
                .bbccccccbbb....
                ..bcccccbbbb....
                ..bcccccbbb.....
                ..bbcccbbb......
                ..bbcccbb.......
                ..bcccccb.......
                ..bcccccb.......
                ..bccccb........
                ..bccccb........
                ..bccccb........
                ..bccccb........
                ..bccccb........
                ..bccccb........
                ..bbcccb........
                ...bcccb........
                ...bcccb........
                ...bbcbb........
                ....bbbbbb......
                .....bbcccb.....
                .....bbbbb......
                ................
                ................
                `],
            100,
            true
            )
        }
        if (controller.left.isPressed() || controller.right.isPressed()) {
            return
        }
    }
}
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.protection, function (sprite, otherSprite) {
    music.smallCrash.play()
    statusbar.value += -1
    sprite.destroy()
    otherSprite.startEffect(effects.spray, 100)
})
function moveAnim () {
    if (person.isHittingTile(CollisionDirection.Bottom)) {
        animation.stopAnimation(animation.AnimationTypes.All, person)
        release2 = 1
        if ("right" == direction) {
            animation.runImageAnimation(
            person,
            [img`
                ................
                ................
                ................
                ................
                ................
                ......bbbb......
                ....bbbccb......
                ....bcccccb.....
                ....bcccccbb....
                ...bbbbccccb....
                ...bbbbcccbb....
                ...bccbbbbb.....
                ...bcccbb.......
                ..bbcccbb.......
                .bbccccbb.......
                .bcccccbb.......
                .bcccccbb.......
                .bcccccbbb......
                .bccccccbb......
                .bccccccbbb.....
                .bcccccccbb.....
                .bcccccccbb.....
                .bbccccccbbb....
                ..bcccccbbbb....
                ..bcccccbbb.....
                ..bbcccbbb......
                ..bbcccbb.......
                ..bcccccb.......
                ..bcccccb.......
                ..bcccccb.......
                ..bccccb........
                ..bccccb........
                ..bccccb........
                ..bccccb........
                ..bccccb........
                ..bccccb........
                ..bbcccb........
                ...bcccb........
                ...bcccb........
                ...bbcbb........
                ....bbbbbb......
                .....bbcccb.....
                .....bbbbb......
                ................
                ................
                `,img`
                ................
                ................
                ................
                ................
                ................
                ................
                ......bbbb......
                ....bbbccb......
                ....bcccccb.....
                ...bbcccccbb....
                ...bbbbccccb....
                ...bbbbcccbb....
                ...bccbbbbb.....
                ..bbcccbb.......
                .bbccccbb.......
                .bcccccbb.......
                .bcccccbb.......
                .bcccccbbb......
                .bccccccbb......
                .bccccccbbb.....
                .bcccccccbb.....
                .bcccccccbb.....
                .bbccccccbbb....
                ..bcccccbbbb....
                ..bcccccbbb.....
                ..bbcccbbb......
                ..bbcccbb.......
                ..bcccccb.......
                ..bcccccb.......
                ..bcccccb.......
                ..bccccbcb......
                ..bccccbcb......
                ..bccccbcb......
                ..bccccbccb.....
                ..bccccbccb.....
                ..bccccbccb.....
                ..bbcccbcb......
                ...bcccbbb......
                ...bcccbb.......
                ...bbcbb........
                ....bbbbbb......
                .....bbcccb.....
                .....bbbbb......
                ................
                ................
                `,img`
                ................
                ................
                ................
                ................
                ................
                ......bbbb......
                ....bbbccb......
                ....bcccccb.....
                ....bcccccbb....
                ...bbbbccccb....
                ...bbbbcccbb....
                ...bccbbbbb.....
                ...bcccbb.......
                ..bbcccbb.......
                .bbccccbb.......
                .bcccccbb.......
                .bcccccbb.......
                .bcccccbbb......
                .bccccccbb......
                .bccccccbbb.....
                .bcccccccbb.....
                .bcccccccbb.....
                .bbccccccbbb....
                ..bcccccbbbb....
                ..bcccccbbb.....
                ..bbcccbbb......
                ..bbcccbb.......
                ..bcccccb.......
                ..bcccccb.......
                ..bcccccbb......
                ..bccccbcbb.....
                ..bccccbccb.....
                ..bccccbcccb....
                ..bcccbbbccb....
                ..bcccb.bccb....
                ..bcccb.bccb....
                ..bbccbbcccb....
                ...bccbcccbb....
                ...bccbccbb.....
                ...bbcbccbb.....
                ....bbbbbbbbb...
                .....bbcccccb...
                .....bbbbbbb....
                ................
                ................
                `,img`
                ................
                ................
                ................
                ................
                ................
                ................
                ......bbbb......
                ....bbbccb......
                ....bcccccb.....
                ...bbcccccbb....
                ...bbbbccccb....
                ...bbbbcccbb....
                ...bccbbbbb.....
                ..bbcccbb.......
                .bbccccbb.......
                .bcccccbb.......
                .bcccccbb.......
                .bcccccbbb......
                .bccccccbb......
                .bccccccbbb.....
                .bcccccccbb.....
                .bcccccccbb.....
                .bbccccccbbb....
                ..bcccccbbbb....
                ..bcccccbbb.....
                ..bbcccbbb......
                ..bbcccbb.......
                ..bcccccb.......
                ..bcccccbb......
                ..bcccccbb......
                ..bccccbcbb.....
                ..bbcccbccb.....
                ...bcccbccbb....
                ...bcccbcccb....
                ...bcccbbcccb...
                ..bcccc.bcccb...
                ..bcccb.bbccb...
                ..bcccb..bbccb..
                ...bccbb..bcccb.
                ...bcccbb..bbb..
                ...bccccb.......
                ....bbbbb.......
                ................
                ................
                ................
                `,img`
                ................
                ................
                ................
                ................
                ................
                ......bbbb......
                ....bbbccb......
                ....bcccccb.....
                ....bcccccbb....
                ...bbbbccccb....
                ...bbbbcccbb....
                ...bccbbbbb.....
                ...bcccbb.......
                ..bbcccbb.......
                .bbccccbb.......
                .bcccccbb.......
                .bcccccbb.......
                .bcccccbbb......
                .bccccccbb......
                .bccccccbbb.....
                .bcccccccbb.....
                .bcccccccbb.....
                .bbccccccbbb....
                ..bcccccbbbb....
                ..bcccccbbb.....
                ..bbcccbbb......
                ..bbcccbb.......
                ...bccccb.......
                ...bccccb.......
                ....bcccbb......
                ....bccccbb.....
                ....bcccccb.....
                ....bcccccb.....
                ....bcccccb.....
                ....bcccccb.....
                ....bcccccb.....
                ....cccccbb.....
                ...bcccccb......
                ...bcccccb......
                ...bbcccb.......
                ....bbccb.......
                .....bbbcb......
                .......bbb......
                ................
                ................
                `,img`
                ................
                ................
                ................
                ................
                ................
                ......bbbb......
                ....bbbccb......
                ....bcccccb.....
                ....bcccccbb....
                ...bbbbccccb....
                ...bbbbcccbb....
                ...bccbbbbb.....
                ...bcccbb.......
                ..bbcccbb.......
                .bbccccbb.......
                .bcccccbb.......
                .bcccccbb.......
                .bcccccbbb......
                .bccccccbb......
                .bccccccbbb.....
                .bcccccccbb.....
                .bcccccccbb.....
                .bbccccccbbb....
                ..bcccccbbbb....
                ..bcccccbbb.....
                ..bbcccbbb......
                ..bbcccbb.......
                ..bcccccb.......
                ..bcccccb.......
                ..bcccccb.......
                ..bccccb........
                ..bbcccb........
                ..bcbccbb.......
                .bbcbcccb.......
                .bccbbcccb......
                .bccbbcccbb.....
                .bccbbbbccbb....
                .bcccb.bcccb....
                .bbcb..bccccb...
                ..bbb..bccccb...
                ...bb...bbbccbb.
                ..........bbbbb.
                ................
                ................
                ................
                `,img`
                ................
                ................
                ................
                ................
                ................
                ................
                ......bbbb......
                ....bbbccb......
                ....bcccccb.....
                ...bbcccccbb....
                ...bbbbccccb....
                ...bbbbcccbb....
                ...bccbbbbb.....
                ..bbcccbb.......
                .bbccccbb.......
                .bcccccbb.......
                .bcccccbb.......
                .bcccccbbb......
                .bccccccbb......
                .bccccccbbb.....
                .bcccccccbb.....
                .bcccccccbb.....
                .bbccccccbbb....
                ..bcccccbbbb....
                ..bcccccbbb.....
                ..bbcccbbb......
                ..bbcccbb.......
                ..bcccccb.......
                ..bcccccb.......
                ..bccbccb.......
                ..bccbcbb.......
                ..bccbccb.......
                ..bccbcccb......
                ..bccbcccb......
                ..bccbcccbb.....
                ..bccbccccb.....
                .bcccbccccb.....
                .bcccbbcccb.....
                .bccccbccccb....
                ..bcccbbcccb....
                ..bbbbcbbccbb...
                ..bbbbbcbbbbb...
                ....bbbbbb......
                ................
                ................
                `],
            50,
            true
            )
        } else {
            animation.runImageAnimation(
            person,
            [img`
                ................
                ................
                ................
                ................
                ................
                ......bbbb......
                ....bbbccb......
                ....bcccccb.....
                ....bcccccbb....
                ...bbbbccccb....
                ...bbbbcccbb....
                ...bccbbbbb.....
                ...bcccbb.......
                ..bbcccbb.......
                .bbccccbb.......
                .bcccccbb.......
                .bcccccbb.......
                .bcccccbbb......
                .bccccccbb......
                .bccccccbbb.....
                .bcccccccbb.....
                .bcccccccbb.....
                .bbccccccbbb....
                ..bcccccbbbb....
                ..bcccccbbb.....
                ..bbcccbbb......
                ..bbcccbb.......
                ..bcccccb.......
                ..bcccccb.......
                ..bcccccb.......
                ..bccccb........
                ..bccccb........
                ..bccccb........
                ..bccccb........
                ..bccccb........
                ..bccccb........
                ..bbcccb........
                ...bcccb........
                ...bcccb........
                ...bbcbb........
                ....bbbbbb......
                .....bbcccb.....
                .....bbbbb......
                ................
                ................
                `,img`
                ................
                ................
                ................
                ................
                ................
                ................
                ......bbbb......
                ....bbbccb......
                ....bcccccb.....
                ...bbcccccbb....
                ...bbbbccccb....
                ...bbbbcccbb....
                ...bccbbbbb.....
                ..bbcccbb.......
                .bbccccbb.......
                .bcccccbb.......
                .bcccccbb.......
                .bcccccbbb......
                .bccccccbb......
                .bccccccbbb.....
                .bcccccccbb.....
                .bcccccccbb.....
                .bbccccccbbb....
                ..bcccccbbbb....
                ..bcccccbbb.....
                ..bbcccbbb......
                ..bbcccbb.......
                ..bcccccb.......
                ..bcccccb.......
                ..bcccccb.......
                ..bccccbcb......
                ..bccccbcb......
                ..bccccbcb......
                ..bccccbccb.....
                ..bccccbccb.....
                ..bccccbccb.....
                ..bbcccbcb......
                ...bcccbbb......
                ...bcccbb.......
                ...bbcbb........
                ....bbbbbb......
                .....bbcccb.....
                .....bbbbb......
                ................
                ................
                `,img`
                ................
                ................
                ................
                ................
                ................
                ......bbbb......
                ....bbbccb......
                ....bcccccb.....
                ....bcccccbb....
                ...bbbbccccb....
                ...bbbbcccbb....
                ...bccbbbbb.....
                ...bcccbb.......
                ..bbcccbb.......
                .bbccccbb.......
                .bcccccbb.......
                .bcccccbb.......
                .bcccccbbb......
                .bccccccbb......
                .bccccccbbb.....
                .bcccccccbb.....
                .bcccccccbb.....
                .bbccccccbbb....
                ..bcccccbbbb....
                ..bcccccbbb.....
                ..bbcccbbb......
                ..bbcccbb.......
                ..bcccccb.......
                ..bcccccb.......
                ..bcccccbb......
                ..bccccbcbb.....
                ..bccccbccb.....
                ..bccccbcccb....
                ..bcccbbbccb....
                ..bcccb.bccb....
                ..bcccb.bccb....
                ..bbccbbcccb....
                ...bccbcccbb....
                ...bccbccbb.....
                ...bbcbccbb.....
                ....bbbbbbbbb...
                .....bbcccccb...
                .....bbbbbbb....
                ................
                ................
                `,img`
                ................
                ................
                ................
                ................
                ................
                ................
                ......bbbb......
                ....bbbccb......
                ....bcccccb.....
                ...bbcccccbb....
                ...bbbbccccb....
                ...bbbbcccbb....
                ...bccbbbbb.....
                ..bbcccbb.......
                .bbccccbb.......
                .bcccccbb.......
                .bcccccbb.......
                .bcccccbbb......
                .bccccccbb......
                .bccccccbbb.....
                .bcccccccbb.....
                .bcccccccbb.....
                .bbccccccbbb....
                ..bcccccbbbb....
                ..bcccccbbb.....
                ..bbcccbbb......
                ..bbcccbb.......
                ..bcccccb.......
                ..bcccccbb......
                ..bcccccbb......
                ..bccccbcbb.....
                ..bbcccbccb.....
                ...bcccbccbb....
                ...bcccbcccb....
                ...bcccbbcccb...
                ..bcccc.bcccb...
                ..bcccb.bbccb...
                ..bcccb..bbccb..
                ...bccbb..bcccb.
                ...bcccbb..bbb..
                ...bccccb.......
                ....bbbbb.......
                ................
                ................
                ................
                `,img`
                ................
                ................
                ................
                ................
                ................
                ......bbbb......
                ....bbbccb......
                ....bcccccb.....
                ....bcccccbb....
                ...bbbbccccb....
                ...bbbbcccbb....
                ...bccbbbbb.....
                ...bcccbb.......
                ..bbcccbb.......
                .bbccccbb.......
                .bcccccbb.......
                .bcccccbb.......
                .bcccccbbb......
                .bccccccbb......
                .bccccccbbb.....
                .bcccccccbb.....
                .bcccccccbb.....
                .bbccccccbbb....
                ..bcccccbbbb....
                ..bcccccbbb.....
                ..bbcccbbb......
                ..bbcccbb.......
                ...bccccb.......
                ...bccccb.......
                ....bcccbb......
                ....bccccbb.....
                ....bcccccb.....
                ....bcccccb.....
                ....bcccccb.....
                ....bcccccb.....
                ....bcccccb.....
                ....cccccbb.....
                ...bcccccb......
                ...bcccccb......
                ...bbcccb.......
                ....bbccb.......
                .....bbbcb......
                .......bbb......
                ................
                ................
                `,img`
                ................
                ................
                ................
                ................
                ................
                ......bbbb......
                ....bbbccb......
                ....bcccccb.....
                ....bcccccbb....
                ...bbbbccccb....
                ...bbbbcccbb....
                ...bccbbbbb.....
                ...bcccbb.......
                ..bbcccbb.......
                .bbccccbb.......
                .bcccccbb.......
                .bcccccbb.......
                .bcccccbbb......
                .bccccccbb......
                .bccccccbbb.....
                .bcccccccbb.....
                .bcccccccbb.....
                .bbccccccbbb....
                ..bcccccbbbb....
                ..bcccccbbb.....
                ..bbcccbbb......
                ..bbcccbb.......
                ..bcccccb.......
                ..bcccccb.......
                ..bcccccb.......
                ..bccccb........
                ..bbcccb........
                ..bcbccbb.......
                .bbcbcccb.......
                .bccbbcccb......
                .bccbbcccbb.....
                .bccbbbbccbb....
                .bcccb.bcccb....
                .bbcb..bccccb...
                ..bbb..bccccb...
                ...bb...bbbccbb.
                ..........bbbbb.
                ................
                ................
                ................
                `,img`
                ................
                ................
                ................
                ................
                ................
                ................
                ......bbbb......
                ....bbbccb......
                ....bcccccb.....
                ...bbcccccbb....
                ...bbbbccccb....
                ...bbbbcccbb....
                ...bccbbbbb.....
                ..bbcccbb.......
                .bbccccbb.......
                .bcccccbb.......
                .bcccccbb.......
                .bcccccbbb......
                .bccccccbb......
                .bccccccbbb.....
                .bcccccccbb.....
                .bcccccccbb.....
                .bbccccccbbb....
                ..bcccccbbbb....
                ..bcccccbbb.....
                ..bbcccbbb......
                ..bbcccbb.......
                ..bcccccb.......
                ..bcccccb.......
                ..bccbccb.......
                ..bccbcbb.......
                ..bccbccb.......
                ..bccbcccb......
                ..bccbcccb......
                ..bccbcccbb.....
                ..bccbccccb.....
                .bcccbccccb.....
                .bcccbbcccb.....
                .bccccbccccb....
                ..bcccbbcccb....
                ..bbbbcbbccbb...
                ..bbbbbcbbbbb...
                ....bbbbbb......
                ................
                ................
                `],
            50,
            true
            )
        }
        if (controller.left.isPressed() || controller.right.isPressed()) {
            return
        }
    }
}
let rain: Sprite = null
let release1 = 0
let release2 = 0
let person: Sprite = null
let movementSpeed = 0
let direction = ""
let canJump = 0
let statusbar: StatusBarSprite = null
createLevel()
createCharacter()
let umbrellaBig1 = sprites.create(img`
    ....................................................................................................
    ....................................................................................................
    ....................................................................................................
    ....................................................................................................
    ....................................................................................................
    ....................................................................................................
    ....................................................................................................
    ....................................................................................................
    ....................................................................................................
    ....................................................................................................
    ....................................................................................................
    ....................................................................................................
    ....................................................................................................
    ..................................ccc...............................................................
    .................................ccbbcc.............................................................
    .................................cbbbbbcc...........................................................
    ................................cccbbbbbbcc.........................................................
    ................................cbccbbbbbcc.........................................................
    ................................cbbcbbbbbcbc........................................................
    ...............................cbbbcbbbbbcbbcc......................................................
    ...............................cbbbccbbbbcbbbbc.....................................................
    ..............................cbbbbbcbbbbcbbbbbcc...................................................
    ..............................cbbbbbccbbbccbbbbbbc..................................................
    .............................cbbbbbbbcbbbbcbbbbbbbcc................................................
    .............................cbbbbbbbcbbbbcbbbbbbbbbc...............................................
    ............................ccbbbbbbbcbbbbcbbbbbbbbbbc..............................................
    ............................cbbbbbbbbcbbbbcbbbbbbbbbbbcc............................................
    ...........................cbbbbbbbbbcbbbbccbbbbbbbbbbbbccc.........................................
    ..........................cbbbbbbbbbbcbbbbbcbbbbbbbbbbbbcbbc........................................
    ..........................cbbbbbbbbbbcbbbbbcbbbbbbbbbbbbcbbbccc.....................................
    .........................cbbbbbbbbbbbcbbbbbcbbbbbbbbbbbbbcbbbbbc....................................
    .......................cccbbbbbbbbbbbcbbbbbccbbbbbbbbbbbbcbbbbbbcc..................................
    ......................cbbcbbbbbbbbbbbcbbbbbbcbbbbbbbbbbbbccbbbbbbbc.................................
    ....................ccbbbcbbbbbbbbbbbcbbbbbbccbbbbbbbbbbbbcbbbbbbbbcccc.............................
    ...................ccbbbbccbbbbbbbbbbcbbbbbbbcbbbbbbbbbbbbbcbbbbbbbbbbbc............................
    ...................cbbbbbbcbbbbbbbbbbcbbbbbbbbcbbbbbbbbbbbbcbbbbbbbbbbbbcccc........................
    ..................cbbbbbbbcbbbbbbbbbbcbbbbbbbbcbbbbbbbbbbbbbccbbbbbbbbbbbbbbccccc...................
    .................cbbbbbbbbcbbbbbbbbbbcbbbbbbbbbcbbbbbbbbbbbbbccbbbbbbbbbbbbbbbbbccc.................
    ................cbbbbbbbbbcbbbbbbbbbbcbbbbbbbbbbcbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbc.................
    ...............cbbbbbbbbbbcbbbbbbbbbbcbbbbbbbbbbbcbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbc.................
    ..............cbbbbbbbbbbbcbbbbbbbbbbcbbbbbbbbbbbbccbbbbbbbbbbbbbccbbbbbbbbbbbbbbbc.................
    .............cbbbbbbbbbbbbcbbbbbbbbbbcbbbbbbbbbbbbbcbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbc.................
    ............cbbbbbbbbbbbbbcbbbbbbbbbbcbbbbbbbbbbbbbccbbbbbbbbbbbbbbccbbbbbbbbbbbbbcc................
    ...........cbbbbbbbbbbbbbbcbbbbbbbbbbcbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbcbbbbbbbbbbbbbc................
    .........ccbbbbbbbbbbbbbbcbbbbbbbbbbbcbbbbbbbbbbbbbbbccbbbbbbbbbbbbbbcccbbbbbbbbbbbc................
    ........cbbbbbbbbbbbbbbbbcbbbbbbbbbbbcbbbbbbbbbbbbbbbbccbbbbbbbbbbbbbbbbccbbbbbbbbbc................
    ........cbbbbbbbbbbbbbbbccbbbbbbbbbbccbbbbbbbbbbbbbbbbbccbbbbbbbbbbbbbbbbbcccbbbbbbc................
    .......cbbbbbbbbbbbbbbbbcbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbccbbbbc.................
    ......cbbbbbbbbbbbbbbbbbcbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbccbbbbbbbbbbbbbbbbbbbccccc.................
    .....cbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbccbbbbbbbbbbbbbbbbbbbbbc..................
    ....cbbbbbbbbbbbbbbbbbbccbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbccbbbbbbbbbbbbbbbbbbbc...................
    .....ccbbbbbbbbbbbbbbbccbbbbbbbbbbbccbbbbbbbbbbbbbbbbbbbbbbbccbbbbbbbbbbbbbbbccc....................
    ......cccbbbbbbbbbbbbccbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbcccbbbbbbbbbbbbc.......................
    ........cccbbbbbbbbbccbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbccbbbbbbbbbcc........................
    ...........cbbbbbbbccbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccbbbbbc..........................
    ............cccbbbcbbbbbbbbbbbbbbccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccc...........................
    ..............ccccbbbbbbbbbbbbbbccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccc..............................
    .................cccbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccc.................................
    ....................cccbbbbbbbccbbbbbbbbbbbbbbbbccccccccccc.........................................
    .......................ccbbbccbbbbcccccccccccccc....................................................
    ........................cccccccccc........dddddd....................................................
    ...........................................ddddd....................................................
    ...........................................ddddd....................................................
    ............................................ddddd...................................................
    .............................................dddd...................................................
    .............................................ddddd..................................................
    .............................................ddddd..................................................
    .............................................ddddd..................................................
    .............................................ddddd..................................................
    .............................................ddddd..................................................
    ..............................................dddd..................................................
    ..............................................dddd..................................................
    ..............................................dddd..................................................
    ..............................................dddd..................................................
    ..............................................dddd..................................................
    ..............................................dddd..................................................
    ..............................................dddd..................................................
    ..............................................dddd..................................................
    ..............................................dddd..................................................
    ..............................................dddd..................................................
    ..............................................dddd..................................................
    ..............................................dddd..................................................
    ..............................................dddd..................................................
    .............................................ddddd..................................................
    .............................................dddd...................................................
    .............................................dddd...................................................
    .............................................dddd...................................................
    ..............................................ddd...................................................
    ....................................................................................................
    ....................................................................................................
    `, SpriteKind.protection)
let umbrella = sprites.create(img`
    .........................
    .........cccc............
    .......ccbbccc...........
    .....ccbbccbcbcc.........
    ...ccbbbccbbccbbc........
    ..cbbbbccbbbcbcbbc.......
    .cbbbcccbbbbcbccbbc......
    ..ccbcbbbbbbcbbcbbbc.....
    ....cccbbbbbcbbbccbbc....
    .......ccbbccbbbbccbc....
    .........ccccccccccc.....
    ...........c.............
    ...........c.............
    ...........c.............
    ..........cc.............
    ..........c..............
    ..........c..............
    .........cc..............
    .........c...............
    .........c...............
    `, SpriteKind.protection)
umbrellaBig1.z = 4
umbrellaBig1.setPosition(20, 120)
statusbar = statusbars.create(20, 4, StatusBarKind.Health)
statusbar.value = 100
statusbar.attachToSprite(umbrella)
game.onUpdateInterval(0.5, function () {
    rain = sprites.createProjectileFromSide(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . 7 . . . . . . . . 
        . . . . . . . 7 . . . . . . . . 
        . . . . . . . 7 . . . . . . . . 
        . . . . . . . 7 . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, randint(0, -100), 1500)
    rain.startEffect(effects.spray, 100)
    rain.setPosition(randint(-160, 160) + person.x, 87)
})
forever(function () {
    umbrella.setPosition(5 + person.x, person.y - 16)
    if (statusbar.value < 1) {
        game.over(false)
    }
})
forever(function () {
    if (person.isHittingTile(CollisionDirection.Bottom)) {
        if (controller.up.isPressed() && 1 == canJump) {
            if (direction == "left") {
                person.vx += -70
            }
            if (direction == "right") {
                person.vx += 70
            }
            canJump = 0
            animation.stopAnimation(animation.AnimationTypes.All, person)
            person.vy = -40
            music.jumpUp.play()
            pause(1000)
            canJump = 1
            neutralAnim()
        }
        if (controller.left.isPressed()) {
            scroller.scrollBackgroundWithSpeed(50, 0)
            direction = "left"
            person.vx = movementSpeed * -1
        } else {
            if (controller.right.isPressed()) {
                scroller.scrollBackgroundWithSpeed(-50, 0)
                direction = "right"
                person.vx = movementSpeed
            } else {
                scroller.scrollBackgroundWithSpeed(0, 0)
                person.vx = 0
            }
        }
        if (controller.left.isPressed() && controller.right.isPressed()) {
            scroller.scrollBackgroundWithSpeed(0, 0)
            person.vx = 0
            animation.stopAnimation(animation.AnimationTypes.All, person)
            neutralAnim()
        }
    }
})
